name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'ExceptionHelpers.sln'
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore
      
    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/tags/release')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
